services:
  app:
    image: ghcr.io/sd2-2024-group-25/dungeon-revealer-app:latest
    environment:
      - NODE_ENV=production
      - WATCH_MODE=true # Enable file watching inside Docker
    ports:
      - "3000:3000"
    command: ["sh", "-c", "node server-build/index.js & node public/research/data.js"]
    volumes:
      - dungeon_revealer_data:/usr/src/dungeon-revealer/public/research/whiteboard  # Shared volume
    networks:
      - excalidraw-network  # Add this to join the network

  excalidraw:
    image: ghcr.io/sd2-2024-group-25/excalidraw:latest
    container_name: excalidraw
    ports:
      - "5000:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules

  excalidraw-room:
    image: ghcr.io/sd2-2024-group-25/excalidraw-room:latest
    ports:
      - "3002:3002"
    networks:
      - excalidraw-network
    volumes:
      - ./excalidraw-room:/usr/src/excalidraw-room
    environment:
      - NODE_ENV=production

  excalidraw-storage-backend:
    image: ghcr.io/sd2-2024-group-25/excalidraw-storage-backend:latest
    ports:
      - "8080:8080"
    networks:
      - excalidraw-network
    volumes:
      - ./excalidraw-storage-backend:/usr/src/excalidraw-storage-backend
      - ./uploads:/usr/src/excalidraw-storage-backend/uploads  # Explicitly map uploads directory
      - dungeon_revealer_data:/usr/src/dungeon-revealer/public/research/whiteboard  # Shared volume
    environment:
      - NODE_ENV=production

volumes:
  notused:
  uploads:
  dungeon_revealer_data:

networks:
  excalidraw-network:

