services:
  app:
    build:
      context: ./dungeon-revealer
    environment:
      - NODE_ENV=production
      - WATCH_MODE=true # Enable file watching inside Docker
    ports:
      - "3000:3000"
    command: ["sh", "-c", "node server-build/index.js & node public/research/data.js"]
    volumes:
      - dungeon_revealer_data:/usr/src/dungeon-revealer/public/research/whiteboard  # Shared volume
    networks:
      - excalidraw-network  # Add this to join the network

  excalidraw:
    build:
      context: ./excalidraw
      args:
        - NODE_ENV=development
    container_name: excalidraw
    ports:
      - "5000:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules

  excalidraw-room:
    build:
      context: ./excalidraw-room
    ports:
      - "3002:3002"
    networks:
      - excalidraw-network
    volumes:
      - ./excalidraw-room:/usr/src/excalidraw-room
    environment:
      - NODE_ENV=production

  excalidraw-storage-backend:
    build:
      context: ./excalidraw-storage-backend
    ports:
      - "8080:8080"
    networks:
      - excalidraw-network
    volumes:
      - ./excalidraw-storage-backend:/usr/src/excalidraw-storage-backend
      - ./uploads:/usr/src/excalidraw-storage-backend/uploads  # Explicitly map uploads directory
      - dungeon_revealer_data:/usr/src/dungeon-revealer/public/research/whiteboard  # Shared volume
    environment:
      - NODE_ENV=production
volumes:
  notused:
  uploads:
  dungeon_revealer_data:

networks:
  excalidraw-network:

